name: Run Manual Unit Tests for PR Review

on:
  workflow_dispatch:  # Allows manual triggering of workflow
    inputs:
      pr_number:
        description: 'PR Number'
        required: true
        default: 3 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn
      - name: List directory contents
        run: |
          ls -R
      - name: Check file permissions
        run: ls -l data/spambase.csv
      - name: Print current working directory
        run: pwd

      - name: List all files in the working directory
        run: ls -R
        
      - name: Check if CSV loads correctly
        run: python -c "import pandas as pd; df = pd.read_csv('data/spambase.csv', header=None); print(df.head())"

        


          

      
      - name: Run unit tests
        id: tests
        run: python -m unittest test_code.py  # This runs the test file

     
